#pragma once

#define GL_TOTAL_VERTICES_FLOAT_VALUES_PER_TETRA 36
#define FACETS_PER_TETRA 4
#define VERTICES_PER_TETRA_FACET 3
#define UNIQUE_VERTICES_PER_TETRA 4
#define MESH_FACE_VERTICES 3
#define FACETS_PER_CUBE 6
#define VERTICES_PER_CUBE_FACET 4

#define VERTEX_ATTRIBUTES 2